name: SuperSmashKit
version: 1.0.0
description: Handles all kit mechanics.
author: George Bakewell
main: io.github.theonlygusti.supersmashkit.Plugin
depend: [ LibsDisguises ]
commands:
  kit:
    description: Equips a kit
    permission: supersmashkit.kit
    usage: "§cUsage: /<command> $r"
    aliases: []
