name: SuperSmashAPI
version: 1.0.0
description: Handles all game mechanics and provides an API for designing kits.
author: George Bakewell
authors: [ Tobi ]
main: io.github.theonlygusti.ssapi.Plugin
depend: [ LibsDisguises ]
commands:
  kit:
    description: Equips a kit
    permission: ssapi.kitcmd
    usage: "§cUsage: /<command> <name>§r"
    aliases: []
  dekit:
    description: Unequips the kit that is currently equipped
    permission: ssapi.dekitcmd
    usage: "§cUsage: /<command>§r"
    aliases: []
